 # Class 2, in-class work<br>
 Date: 1/25/2018
 


In [1]:
my_string = "hello world"

In [3]:
print(my_string)

hello world


## SLICING <br>
syntax of a slice: `my_string[start:end]` where `end` is not inclusive


In [18]:
my_string[0:-1] #slice


'hello worl'

Here is how to know the length of a string: len()

In [17]:
len(my_string)

11

In [20]:
my_string[0:len(my_string)-1]

'hello worl'

In [21]:
my_string[::-1]

'dlrow olleh'

In [31]:
string = "banana"

In [36]:
string[1:len(string)-2]

'ana'

## Slicing on Numpy Arrays <br>
Arrays are the essential data structure in numerical computing! They are available via the numpy library.


In [37]:
import numpy as np


In [41]:
x = np.array([2,4,6,8])

In [42]:
x[0]

2

In [43]:
x[1:3]

array([4, 6])

In [49]:
my_array = np.linspace(0,100,26)

In [50]:
my_array[-1]

100.0

In [51]:
print(my_array)

[   0.    4.    8.   12.   16.   20.   24.   28.   32.   36.   40.   44.
   48.   52.   56.   60.   64.   68.   72.   76.   80.   84.   88.   92.
   96.  100.]


In [52]:
my_array[3:12]

array([ 12.,  16.,  20.,  24.,  28.,  32.,  36.,  40.,  44.])

In [54]:
y = np.arange(0,100,4)

In [55]:
y


array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [56]:
type(string)

str